In [1]:
import pandas as pd
from googlemaps import Client as GoogleMaps
import time

In [2]:
df = pd.read_csv('housing_data_dirty.csv')

In [3]:
df['address'] = df['address'].str.replace('Sales Office: ', '')

In [5]:
gmaps = GoogleMaps('ENTER_API_KEY_HERE')

In [6]:
df['long'] = ""
df['lat'] = ""

In [7]:
for x in range(len(df['address'].values)):
    try:
        time.sleep(1) #to add delay in case of large DFs
        geocode_result = gmaps.geocode(df['address'][x])
        df['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
        df['long'][x] = geocode_result[0]['geometry']['location']['lng']
    except IndexError:
        print("Address was wrong...")
    except Exception as e:
        print("Unexpected error occurred.", e )
df.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Address was wrong...
Address was wrong...

,web-scraper-order,web-scraper-start-url,link,link-href,price,beds,bath,sqft,lot_size,car1,car2?,address,long,lat
0,1669705518-2804,https://www.realtor.com/realestateandhomes-sea...,NaN,https://www.realtor.com/realestateandhomes-det...,"$775,000",2bed,2bath,"1,025",NaN,$756,1 car,"350 11th Ave Unit 725, San Diego, CA 92101",-117.155077,32.708849
1,1669705523-2805,https://www.realtor.com/realestateandhomes-sea...,NaN,https://www.realtor.com/realestateandhomes-det...,"$309,900",1bed,1bath,507,1.57,$611,1986,"859 W San Ysidro Blvd Unit 9, San Ysidro, CA 9...",-117.060656,32.55966
2,1669705529-2806,https://www.realtor.com/realestateandhomes-sea...,NaN,https://www.realtor.com/realestateandhomes-det...,"$1,349,000",4bed,2.5bath,"2,068",NaN,$652,2 cars,"11888 Miro Cir, San Diego, CA 92131",-117.105908,32.91949
3,1669705533-2807,https://www.realtor.com/realestateandhomes-sea...,NaN,https://www.realtor.com/realestateandhomes-det...,"$875,000",2bed,2bath,"1,100",NaN,$795,1 car,"4944 Cass St Unit 903, San Diego, CA 92109",-117.254479,32.804454
4,1669705537-2808,https://www.realtor.com/realestateandhomes-sea...,NaN,https://www.realtor.com/realestateandhomes-det...,"$2,200,000",14bed,14bath,"4,242","5,372",4 cars,1981,"4046 Honeycutt St, San Diego, CA 92109",-117.232658,32.794588

In [8]:
df2 = df[['price','beds','bath','sqft','lot_size','address','lat','long']]

In [9]:
df2.head(50)

,price,beds,bath,sqft,lot_size,address,lat,long
0,"$775,000",2bed,2bath,"1,025",NaN,"350 11th Ave Unit 725, San Diego, CA 92101",32.708849,-117.155077
1,"$309,900",1bed,1bath,507,1.57,"859 W San Ysidro Blvd Unit 9, San Ysidro, CA 9...",32.55966,-117.060656
2,"$1,349,000",4bed,2.5bath,"2,068",NaN,"11888 Miro Cir, San Diego, CA 92131",32.91949,-117.105908
3,"$875,000",2bed,2bath,"1,100",NaN,"4944 Cass St Unit 903, San Diego, CA 92109",32.804454,-117.254479
4,"$2,200,000",14bed,14bath,"4,242","5,372","4046 Honeycutt St, San Diego, CA 92109",32.794588,-117.232658
5,"$1,935,900",4bed,4.5bath,"3,520",NaN,"11051 Mont Blanc Drive, San Diego, CA 92126",32.898832,-117.165077
6,"$1,264,900",4bed,4bath,"2,464",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
7,"$1,254,900",4bed,4bath,"2,464",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
8,"$1,840,900",4bed,4.5bath,"3,341",NaN,"11051 Mont Blanc Drive, San Diego, CA 92126",32.898832,-117.165077
9,"$1,289,900",4bed,4bath,"2,460",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
10,"$2,227,900",5bed,4.5bath,"3,643",NaN,"11051 Mont Blanc Drive, San Diego, CA 92126",32.898832,-117.165077
11,"$1,810,900",4bed,4.5bath,"3,157",NaN,"11051 Mont Blanc Drive, San Diego, CA 92126",32.898832,-117.165077
12,"$4,966,000",3bed,2bath,"3,064",0.32,"7170 Encelia Dr, La Jolla, CA 92037",32.839392,-117.25776
13,"$968,000",2bed,2bath,"1,770",0.29,"16171 Selva Dr, Sandiego San Diego, CA 92128",33.006246,-117.061548
14,"$799,900",4bed,3bath,"1,340","5,300","2595 Elm Ave, San Diego, CA 92154",32.579908,-117.077776
15,"$724,000",4bed,2bath,"1,484",0.98,"1909 Mesa Hills Ct, San Diego, CA 92114",32.691464,-117.046055
16,"$12,990,000",7bed,8.5+bath,"9,726",0.5,"744 Muirlands Vista Way, La Jolla, CA 92037",32.826056,-117.269862
17,"$643,000",4bed,3bath,"1,701","2,617","1223 Manzana Way, San Diego, CA 92139",32.693271,-117.026008
18,"$499,000",2bed,1.5bath,866,NaN,"6555 Mount Ada Rd Unit 119, San Diego, CA 92111",32.819056,-117.173434
19,"$1,249,000",5bed,3.5bath,"2,246",0.3,"6328 Lake Shore Dr, San Diego, CA 92119",32.795456,-117.036607
20,"$1,425,000",4bed,2bath,"2,068","7,400","10079 Wildlife Rd, San Diego, CA 92131",32.90831,-117.0815
21,"$812,000",3bed,2.5bath,"1,566","5,500","7441 Westbrook Ave, San Diego, CA 92139",32.683977,-117.028123
22,"$696,000",2bed,2bath,864,14.13,"12550 Carmel Creek Rd Unit 101, San Diego, CA ...",32.944138,-117.231059
23,"$1,998,000",9bed,3.5+bath,"3,802",NaN,"7142 Bobhird Dr, San Diego, CA 92119",32.811533,-117.014053
24,"$2,250,000",4bed,4bath,"3,248",NaN,"2328-34 2nd Ave, San Diego, CA 92101",32.729729,-117.163309
25,"$932,000",3bed,2bath,"1,461","6,497","15767 Caminito Cercado, San Diego, CA 92128",33.002289,-117.076581
26,"$1,136,000",4bed,3bath,"2,040","7,100","10456 LA Morada Dr, San Diego, CA 92124",32.839117,-117.102093
27,"$1,799,990",4bed,4bath,NaN,"2,599","721 Pennsylvania Ave, San Diego, CA 92103",32.744988,-117.157886
28,"$2,850,000",5bed,4.5bath,"2,979",0.24,"13763 Boquita Dr, Del Mar, CA 92014",32.948116,-117.249474
29,"$1,799,000",3bed,2bath,"1,525","4,842","2930 Carleton St, San Diego, CA 92106",32.723061,-117.229879
30,"$1,204,900",3bed,3.5bath,"2,037",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
31,"$1,699,900",4bed,3.5bath,"2,711",NaN,"12671 Stella Lane, San Diego, CA 92129",32.953397,-117.151544
32,"$1,194,900",3bed,3.5bath,"2,050",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
33,"$1,244,900",4bed,3.5bath,"2,291",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
34,"$1,276,900",4bed,3.5bath,"2,316",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
35,"$1,656,000",5bed,3bath,"3,026",NaN,"12671 Stella Lane, San Diego, CA 92129",32.953397,-117.151544
36,"$1,234,900",4bed,3.5bath,"2,289",NaN,"10504 Cara Cara Drive, San Diego, CA 92126",32.89554,-117.161033
37,"$1,635,900",4bed,3bath,"2,493",NaN,"12671 Stella Lane, San Diego, CA 92129",32.953397,-117.151544
38,"$579,000",2bed,1.5bath,884,NaN,"8422 Summerdale Rd Unit B, San Diego, CA 92126",32.91943,-117.143135
39,"$1,100,000",2bed,1bath,838,NaN,"3119 Ingelow St, San Diego, CA 92106",32.72752,-117.22896
40,"$1,169,000",4bed,2bath,"1,826","5,897","5011 E Mountain View Dr, San Diego, CA 92116",32.769303,-117.116801
41,"$5,399,500",4bed,4.5bath,"5,080","7,200","7682 Hillside Dr, La Jolla, CA 92037",32.84586,-117.258679
42,"$659,000",2bed,2bath,"1,349",NaN,"6347 Rancho Mission Rd Unit 2, San Diego, CA 9...",32.788817,-117.10762
43,"$4,099,999",3bed,3bath,"2,588","5,915","5485 Calumet Ave, La Jolla, CA 92037",32.811642,-117.269196
44,"$499,000",2bed,2bath,"1,387","5,000","3629 Gilmore St, San Diego, CA 92113",32.702937,-117.116203
45,"$1,599,900",4bed,2bath,"2,008","5,500","4862 Viane Way, San Diego, CA 92110",32.778185,-117.197768
46,"$725,000",NaN,NaN,NaN,NaN,"1325 S 45th St Unit 1, San Diego, CA 92113",32.692797,-117.097818
47,"$550,000",2bed,1bath,"1,000","7,400","16953 Hierba Dr, San Diego, CA 92128",33.020195,-117.070628
48,"$899,000",2bed,2bath,803,NaN,"5027 Santa Monica Ave Apt A, San Diego, CA 92107",32.747766,-117.251123
49,"$669,000",3bed,2.5bath,"1,649","3,826","7978 Tinaja Ln, San Diego, CA 92139",32.695846,-117.023111

In [12]:
df2.to_csv('with_coor.csv')